// file: TaxonomyKbBeanFactoryException.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.taxonomy;


/** file: TaxonomyKbBeanFactoryException.java
 * @author ontology bean generator
 * @version 2009/09/30, 13:34:31
 */
public class TaxonomyKbBeanFactoryException extends Exception { 

  private static final long serialVersionUID = -8627856865395943317L;

  public TaxonomyKbBeanFactoryException(String msg) {
    super(msg);
  }

  public TaxonomyKbBeanFactoryException(String msg, Throwable thr) {
    super(msg, thr);
  }

  public TaxonomyKbBeanFactoryException(Throwable thr) {
    super(thr);
  }

}

