// file: TaxonomyKbBeanFactory.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.taxonomy;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import edu.stanford.smi.protege.model.KnowledgeBase;
import edu.stanford.smi.protege.model.Instance;
import edu.stanford.smi.protege.model.Slot;

import ontology.common.*;

/** file: TaxonomyKbBeanFactory.java
 * @author ontology bean generator
 * @version 2009/09/30, 13:34:31
 */
public class TaxonomyKbBeanFactory {
  private static final long serialVersionUID = -8627856865395943317L;

  private KnowledgeBase kb = null;
  private java.util.HashMap<String, Object> beanInstances = null;
  public static java.util.HashMap<String, String> typeToMethodName = new java.util.HashMap<String, String> ();

  //private Object tempAnyValue;
  //private Boolean tempBooleanValue;
  //private Class tempClsValue;
  private Float tempFloatValue;
  private Instance tempInstanceValue;
  //private Integer tempIntegerValue;
  private String tempStringValue;
  private String tempSymbolValue;

  //private java.util.ArrayList  tempAnyValues;
  //private java.util.ArrayList <Boolean> tempBooleanValues;
  //private java.util.ArrayList <Class> tempClsValues;
  //private java.util.ArrayList <Float> tempFloatValues;
  private java.util.ArrayList <Instance> tempInstanceValues;
  //private java.util.ArrayList <Integer> tempIntegerValues;
  //private java.util.ArrayList <String> tempStringValues;
  //private java.util.ArrayList <String> tempSymbolValues;


  //Constructor(s)
  public TaxonomyKbBeanFactory(KnowledgeBase kb) {
    this.kb = kb;
    beanInstances = new java.util.HashMap<String, Object>();
  }

  /**
   * Protege name: EnvironmentalCategory
  */
  public String getEnvironmentalCategory(String instanceName) throws CommonKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (String)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new CommonKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    String javaInst = new String();

    beanInstances.put(instanceName, javaInst);

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst = tempStringValue;
    }

    return javaInst;
  }

  /**
   * It's a subclass of a defined term
   * Protege name: Structure
  */
  public String getStructure(String instanceName) throws CommonKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (String)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new CommonKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    String javaInst = null; //OJO

    //javaInst set all properties

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst = tempStringValue;
    }
    
    beanInstances.put(instanceName, javaInst);
    
    return javaInst;
  }

  /**
   * It's a subclass of a defined term
   * Protege name: Attribute
  */
  public String getAttribute(String instanceName) throws CommonKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (String)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new CommonKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    String javaInst = null; //OJO

    //javaInst set all properties

    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst = tempStringValue;
    }
    
    beanInstances.put(instanceName, javaInst);

    return javaInst;
  }

  /**
   * It's a subclass of a defined term
   * Protege name: State
  */
  public String getState(String instanceName) throws CommonKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (String)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new CommonKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    String javaInst = null;
    
    tempStringValue = getStringValue( protegeInst, kb.getSlot( "term" ) );
    if (tempStringValue != null) {
      javaInst = tempStringValue;
    }
    
    beanInstances.put(instanceName, javaInst);
    
    return javaInst;
  }
  
  /**
   * Protege name: Taxon
  */
  public Taxon getTaxon(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Taxon)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Taxon javaInst = new Taxon(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties

    tempSymbolValue = getStringValue( protegeInst, kb.getSlot( "level" ) );
    if (tempSymbolValue != null) {
      javaInst.setLevel(tempSymbolValue);
    }
    
    tempStringValue = getStringValue( protegeInst, kb.getSlot( "name" ) );
    if (tempStringValue != null) {
      javaInst.setName(tempStringValue);
    }
    
    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "successors" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addSuccessor( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"successors\" in instance " + instanceName);
        }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "predecessor" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setPredecessor( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"predecessor\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "weightedDescription" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("WeightedDescription") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setWeightedDescription( (WeightedDescription) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"weightedDescription\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: SingleValue
  */
  public SingleValue getSingleValue(String instanceName) throws CommonKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SingleValue)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new CommonKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SingleValue javaInst = new SingleValue(instanceName);

    beanInstances.put(instanceName, javaInst);

    tempSymbolValue = getStringValue( protegeInst, kb.getSlot( "measuringUnit" ) );
    if (tempSymbolValue != null) {
      javaInst.setMeasuringUnit(tempSymbolValue);
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "value" ) );
    if (tempFloatValue != null) {
      javaInst.setValue(tempFloatValue.doubleValue());
    }

    return javaInst;
  }

  /**
   * Protege name: MSCharacterDescriptor
  */
  public MSCharacterDescriptor getMSCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (MSCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    MSCharacterDescriptor javaInst = new MSCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: SVCharacterDescriptor
  */
  public SVCharacterDescriptor getSVCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SVCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SVCharacterDescriptor javaInst = new SVCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValue != null) {
	      try {
	        Object referredBean = getJadeInstanceFor(tempInstanceValue);
	
	        if (referredBean != null) {
	          javaInst.setValue((SingleValue) referredBean);
	        }
	      } catch (TaxonomyKbBeanFactoryException e) {
	        e.printStackTrace();
	      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: RVCharacterDescriptor
  */
  public RVCharacterDescriptor getRVCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (RVCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    RVCharacterDescriptor javaInst = new RVCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setValue( (RangeValue) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: RangeValue
  */
  public RangeValue getRangeValue(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (RangeValue)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    RangeValue javaInst = new RangeValue(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties

    tempSymbolValue = getStringValue( protegeInst, kb.getSlot( "measuringUnit" ) );
    if (tempSymbolValue != null) {
      javaInst.setMeasuringUnit(tempSymbolValue);
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "lowerBound" ) );
    if (tempFloatValue != null) {
      javaInst.setLowerBound(tempFloatValue.doubleValue());
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "upperBound" ) );
    if (tempFloatValue != null) {
      javaInst.setUpperBound(tempFloatValue.doubleValue());
    }

    return javaInst;
  }

  /**
   * Protege name: SSCharacterDescriptor
  */
  public SSCharacterDescriptor getSSCharacterDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SSCharacterDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SSCharacterDescriptor javaInst = new SSCharacterDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setValue( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: SVHeuristicDescriptor
  */
  public SVHeuristicDescriptor getSVHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SVHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SVHeuristicDescriptor javaInst = new SVHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setValue( (SingleValue) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: RVHeuristicDescriptor
  */
  public RVHeuristicDescriptor getRVHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (RVHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    RVHeuristicDescriptor javaInst = new RVHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setValue( (RangeValue) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: Description
  */
  public Description getDescription(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Description)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Description javaInst = new Description(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "descriptors" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("Descriptor") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addDescriptors( (Descriptor) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"descriptors\" in instance " + instanceName);
        }
      }
    }

    return javaInst;
  }

  /**
   * Protege name: SSHeuristicDescriptor
  */
  public SSHeuristicDescriptor getSSHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (SSHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    SSHeuristicDescriptor javaInst = new SSHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setValue( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: MSHeuristicDescriptor
  */
  public MSHeuristicDescriptor getMSHeuristicDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (MSHeuristicDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    MSHeuristicDescriptor javaInst = new MSHeuristicDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "structure" ) );
    if (tempInstanceValue != null) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setStructure( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
    }

    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "score" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addScore( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
      }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "attribute" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Attribute") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setAttribute( (String) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"attribute\" in instance " + instanceName);
        }
    }

    return javaInst;
  }
 
  /**
   * Protege name: WeightedDescriptor
  */
  public WeightedDescriptor getWeightedDescriptor(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (WeightedDescriptor)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    WeightedDescriptor javaInst = new WeightedDescriptor(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "descriptor" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Descriptor") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setDescriptor( (Descriptor) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"descriptor\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "modifier" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Modifier") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setModifier( (Modifier) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"modifier\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: WeightedDescription
  */
  public WeightedDescription getWeightedDescription(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (WeightedDescription)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    WeightedDescription javaInst = new WeightedDescription(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValues = getInstanceValues( protegeInst, kb.getSlot( "weightedDescriptors" ) );
    if (tempInstanceValues != null) {
      for (Instance instValue : tempInstanceValues) {
        tempInstanceValue = instValue;
        if (tempInstanceValue.hasType(kb.getCls("WeightedDescriptor") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.addWeightedDescriptors( (WeightedDescriptor) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"weightedDescriptors\" in instance " + instanceName);
        }
      }
    }

    return javaInst;
  }

  /**
   * Protege name: Modifier
  */
  public Modifier getModifier(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (Modifier)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    Modifier javaInst = new Modifier(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "attributeWeight" ) );
    if (tempFloatValue != null) {
      javaInst.setAttributeWeight(tempFloatValue);
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "structureWeight" ) );
    if (tempFloatValue != null) {
      javaInst.setStructureWeight(tempFloatValue);
    }

    tempFloatValue = getFloatValue( protegeInst, kb.getSlot( "scoreWeight" ) );
    if (tempFloatValue != null) {
      javaInst.setValueWeight(tempFloatValue);
    }

    return javaInst;
  }
  
  /**
   * Protege name: IsSheetTaxon
  */
  public IsSheetTaxon getIsSheetTaxon(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (IsSheetTaxon)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    IsSheetTaxon javaInst = new IsSheetTaxon(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "taxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"taxon\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: IsRootTaxon
  */
  public IsRootTaxon getIsRootTaxon(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (IsRootTaxon)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    IsRootTaxon javaInst = new IsRootTaxon(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "taxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"taxon\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: IsPredecessorTaxonOf
  */
  public IsPredecessorTaxonOf getIsPredecessorTaxonOf(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (IsPredecessorTaxonOf)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    IsPredecessorTaxonOf javaInst = new IsPredecessorTaxonOf(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "subjectTaxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setSubjectTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"subjectTaxon\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "objectTaxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setObjectTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"objectTaxon\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  /**
   * Protege name: IsSuccessorTaxonOf
  */
  public IsSuccessorTaxonOf getIsSuccessorTaxonOf(String instanceName) throws TaxonomyKbBeanFactoryException{
    Object jadeInstance = beanInstances.get(instanceName);
    if (jadeInstance != null)
      return (IsSuccessorTaxonOf)jadeInstance;

    Instance protegeInst = kb.getInstance( instanceName );

    if (protegeInst == null) {
      throw new TaxonomyKbBeanFactoryException("Invalid Protege instance name: " + instanceName + ". No Jade instance was created.");
    }

    IsSuccessorTaxonOf javaInst = new IsSuccessorTaxonOf(instanceName);

    beanInstances.put(instanceName, javaInst);

    //javaInst set all properties


    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "subjectTaxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setSubjectTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"subjectTaxon\" in instance " + instanceName);
        }
    }

    tempInstanceValue = getInstanceValue( protegeInst, kb.getSlot( "objectTaxon" ) );
    if (tempInstanceValue != null) {
        if (tempInstanceValue.hasType(kb.getCls("Taxon") )) {
          try {
            Object referredBean = getJadeInstanceFor(tempInstanceValue);

            if (referredBean != null) {
              javaInst.setObjectTaxon( (Taxon) referredBean);
            }
          } catch (TaxonomyKbBeanFactoryException e) {
            e.printStackTrace();
          }
        }
        else {
          throw new TaxonomyKbBeanFactoryException("Invalid type for instance " + tempInstanceValue + " referred by slot \"objectTaxon\" in instance " + instanceName);
        }
    }

    return javaInst;
  }

  //Typed access methods to slot values
  private static Instance getInstanceValue(Instance theInst, Slot theSlot) {
    return (Instance)theInst.getOwnSlotValue(theSlot);
  }

  @SuppressWarnings("unchecked")
  private static java.util.ArrayList<Instance> getInstanceValues(Instance theInst, Slot theSlot) {
    return new java.util.ArrayList<Instance>(theInst.getOwnSlotValues(theSlot));
  }

  private static Float getFloatValue(Instance theInst, Slot theSlot) {
    return (Float)theInst.getOwnSlotValue(theSlot);
  }

  private static String getStringValue(Instance theInst, Slot theSlot) {
    return (String)theInst.getOwnSlotValue(theSlot);
  }

  public Object getJadeInstanceFor(Instance tempInstanceValue) throws TaxonomyKbBeanFactoryException {
    //TODO test for multiple types
    String methodName = typeToMethodName.get(tempInstanceValue.getDirectType().getName());
    if (methodName != null) {
      try {
        Method method = this.getClass().getMethod(methodName, new Class[] {Class.forName("java.lang.String")});
        return method.invoke(this, new Object[] {tempInstanceValue.getName()});
      }
      catch (SecurityException e) {
         throw new TaxonomyKbBeanFactoryException(e);
      } catch (NoSuchMethodException e) {
         throw new TaxonomyKbBeanFactoryException(e);
      } catch (ClassNotFoundException e) {
         throw new TaxonomyKbBeanFactoryException(e);
      }
      catch (IllegalArgumentException e) {
         throw new TaxonomyKbBeanFactoryException("Exception while invoking method " + methodName + " for instance " + tempInstanceValue.getName(), e);
      } catch (IllegalAccessException e) {
         throw new TaxonomyKbBeanFactoryException("Exception while invoking method " + methodName + " for instance " + tempInstanceValue.getName(), e);
      } catch (InvocationTargetException e) {
         throw new TaxonomyKbBeanFactoryException("Exception while invoking method " + methodName + " for instance " + tempInstanceValue.getName(), e);
      }
    }
    return null;
  }

  static {
    typeToMethodName.put("MSCharacterDescriptor", "getMSCharacterDescriptor");
    typeToMethodName.put("SSCharacterDescriptor", "getSSCharacterDescriptor");
    typeToMethodName.put("RangeValue", "getRangeValue");
    typeToMethodName.put("SingleValue", "getSingleValue");
    typeToMethodName.put("SSHeuristicDescriptor", "getSSHeuristicDescriptor");
    typeToMethodName.put("MSHeuristicDescriptor", "getMSHeuristicDescriptor");
    typeToMethodName.put("SVCharacterDescriptor", "getSVCharacterDescriptor");
    typeToMethodName.put("RVCharacterDescriptor", "getRVCharacterDescriptor");
    typeToMethodName.put("Attribute", "getAttribute");
    typeToMethodName.put("SVHeuristicDescriptor", "getSVHeuristicDescriptor");
    typeToMethodName.put("RVHeuristicDescriptor", "getRVHeuristicDescriptor");
    typeToMethodName.put("Description", "getDescription");
    typeToMethodName.put("Taxon", "getTaxon");
    typeToMethodName.put("State", "getState");
    typeToMethodName.put("WeightedDescriptor", "getWeightedDescriptor");
    typeToMethodName.put("WeightedDescription", "getWeightedDescription");
    typeToMethodName.put("Modifier", "getModifier");
    typeToMethodName.put("EnvironmentalCategory", "getEnvironmentalCategory");
    typeToMethodName.put("Structure", "getStructure");
    typeToMethodName.put("IsSheetTaxon", "getIsSheetTaxon");
    typeToMethodName.put("IsRootTaxon", "getIsRootTaxon");
    typeToMethodName.put("Owns", "getOwns");
    typeToMethodName.put("ApliesTo", "getApliesTo");
    typeToMethodName.put("DescribedBy", "getDescribedBy");
    typeToMethodName.put("Describes", "getDescribes");
    typeToMethodName.put("IsPredecessorTaxonOf", "getIsPredecessorTaxonOf");
    typeToMethodName.put("IsSuccessorTaxonOf", "getIsSuccessorTaxonOf");
  }

}
