// file: CBRKbBeanFactoryException.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.CBR;


/** file: CBRKbBeanFactoryException.java
 * @author ontology bean generator
 * @version 2009/10/6, 23:03:27
 */
public class CBRKbBeanFactoryException extends Exception { 

  private static final long serialVersionUID = 4206237779038972396L;

  public CBRKbBeanFactoryException(String msg) {
    super(msg);
  }

  public CBRKbBeanFactoryException(String msg, Throwable thr) {
    super(msg, thr);
  }

  public CBRKbBeanFactoryException(Throwable thr) {
    super(thr);
  }

}

