// file: KbBasedBeanFactoryException.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.common;


/** file: KbBasedBeanFactoryException.java
 * @author ontology bean generator
 * @version 2009/09/29, 11:00:34
 */
public class CommonKbBeanFactoryException extends Exception { 

  private static final long serialVersionUID = -4182418339071425982L;

  public CommonKbBeanFactoryException(String msg) {
    super(msg);
  }

  public CommonKbBeanFactoryException(String msg, Throwable thr) {
    super(msg, thr);
  }

  public CommonKbBeanFactoryException(Throwable thr) {
    super(thr);
  }

}

