// file: CommonTerminologyOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontology.common;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: CommonTerminologyOntology.java
 * @author ontology bean generator
 * @version 2009/09/29, 11:00:34
 */
public class CommonTerminologyOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = -4182418339071425982L;

  //NAME
  public static final String ONTOLOGY_NAME = "CommonTerminology";
  // The singleton instance of this ontology
  private static Ontology theInstance = new CommonTerminologyOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String MSHEURISTICDESCRIPTOR_VALUE="value";
    public static final String MSHEURISTICDESCRIPTOR="MSHeuristicDescriptor";
    public static final String SSHEURISTICDESCRIPTOR_VALUE="value";
    public static final String SSHEURISTICDESCRIPTOR="SSHeuristicDescriptor";
    public static final String QUALITATIVEHEURISTICDESCRIPTOR="QualitativeHeuristicDescriptor";
    public static final String HEURISTICDESCRIPTOR="HeuristicDescriptor";
    public static final String DESCRIPTION_DESCRIPTORS="descriptors";
    public static final String DESCRIPTION="Description";
    public static final String RVHEURISTICDESCRIPTOR_VALUE="value";
    public static final String RVHEURISTICDESCRIPTOR="RVHeuristicDescriptor";
    public static final String SVHEURISTICDESCRIPTOR_VALUE="value";
    public static final String SVHEURISTICDESCRIPTOR="SVHeuristicDescriptor";
    public static final String QUANTITATIVEHEURISTICDESCRIPTOR="QuantitativeHeuristicDescriptor";
    public static final String SSCHARACTERDESCRIPTOR_VALUE="value";
    public static final String SSCHARACTERDESCRIPTOR="SSCharacterDescriptor";
    public static final String QUALITATIVECHARACTERDESCRIPTOR="QualitativeCharacterDescriptor";
    public static final String CHARACTERDESCRIPTOR="CharacterDescriptor";
    public static final String RANGEVALUE_UPPERBOUND="upperBound";
    public static final String RANGEVALUE_LOWERBOUND="lowerBound";
    public static final String RANGEVALUE="RangeValue";
    public static final String RVCHARACTERDESCRIPTOR_VALUE="value";
    public static final String RVCHARACTERDESCRIPTOR="RVCharacterDescriptor";
    public static final String SVCHARACTERDESCRIPTOR_VALUE="value";
    public static final String SVCHARACTERDESCRIPTOR="SVCharacterDescriptor";
    public static final String QUANTITATIVECHARACTERDESCRIPTOR="QuantitativeCharacterDescriptor";
    public static final String MSCHARACTERDESCRIPTOR_VALUE="value";
    public static final String MSCHARACTERDESCRIPTOR="MSCharacterDescriptor";
    public static final String SINGLEVALUE_VALUE="value";
    public static final String SINGLEVALUE="SingleValue";
    public static final String VALUE_MEASURINGUNIT="measuringUnit";    
    public static final String VALUE="Value";
    public static final String DESCRIPTOR_ATTRIBUTE="attribute";
    public static final String DESCRIPTOR_STRUCTURE="structure";
    public static final String DESCRIPTOR="Descriptor";
    //public static final String MEASURINGUNIT="MeasuringUnit";
    
  /**
   * Constructor
  */
  private CommonTerminologyOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema descriptorSchema = new ConceptSchema(DESCRIPTOR);
    add(descriptorSchema, ontology.common.Descriptor.class);
    ConceptSchema valueSchema = new ConceptSchema(VALUE);
    add(valueSchema, ontology.common.Value.class);
    ConceptSchema singleValueSchema = new ConceptSchema(SINGLEVALUE);
    add(singleValueSchema, ontology.common.SingleValue.class);
    ConceptSchema msCharacterDescriptorSchema = new ConceptSchema(MSCHARACTERDESCRIPTOR);
    add(msCharacterDescriptorSchema, ontology.common.MSCharacterDescriptor.class);
    ConceptSchema quantitativeCharacterDescriptorSchema = new ConceptSchema(QUANTITATIVECHARACTERDESCRIPTOR);
    add(quantitativeCharacterDescriptorSchema, ontology.common.QuantitativeCharacterDescriptor.class);
    ConceptSchema svCharacterDescriptorSchema = new ConceptSchema(SVCHARACTERDESCRIPTOR);
    add(svCharacterDescriptorSchema, ontology.common.SVCharacterDescriptor.class);
    ConceptSchema rvCharacterDescriptorSchema = new ConceptSchema(RVCHARACTERDESCRIPTOR);
    add(rvCharacterDescriptorSchema, ontology.common.RVCharacterDescriptor.class);
    ConceptSchema rangeValueSchema = new ConceptSchema(RANGEVALUE);
    add(rangeValueSchema, ontology.common.RangeValue.class);
    ConceptSchema characterDescriptorSchema = new ConceptSchema(CHARACTERDESCRIPTOR);
    add(characterDescriptorSchema, ontology.common.CharacterDescriptor.class);
    ConceptSchema qualitativeCharacterDescriptorSchema = new ConceptSchema(QUALITATIVECHARACTERDESCRIPTOR);
    add(qualitativeCharacterDescriptorSchema, ontology.common.QualitativeCharacterDescriptor.class);
    ConceptSchema ssCharacterDescriptorSchema = new ConceptSchema(SSCHARACTERDESCRIPTOR);
    add(ssCharacterDescriptorSchema, ontology.common.SSCharacterDescriptor.class);
    ConceptSchema quantitativeHeuristicDescriptorSchema = new ConceptSchema(QUANTITATIVEHEURISTICDESCRIPTOR);
    add(quantitativeHeuristicDescriptorSchema, ontology.common.QuantitativeHeuristicDescriptor.class);
    ConceptSchema svHeuristicDescriptorSchema = new ConceptSchema(SVHEURISTICDESCRIPTOR);
    add(svHeuristicDescriptorSchema, ontology.common.SVHeuristicDescriptor.class);
    ConceptSchema rvHeuristicDescriptorSchema = new ConceptSchema(RVHEURISTICDESCRIPTOR);
    add(rvHeuristicDescriptorSchema, ontology.common.RVHeuristicDescriptor.class);
    ConceptSchema descriptionSchema = new ConceptSchema(DESCRIPTION);
    add(descriptionSchema, ontology.common.Description.class);
    ConceptSchema heuristicDescriptorSchema = new ConceptSchema(HEURISTICDESCRIPTOR);
    add(heuristicDescriptorSchema, ontology.common.HeuristicDescriptor.class);
    ConceptSchema qualitativeHeuristicDescriptorSchema = new ConceptSchema(QUALITATIVEHEURISTICDESCRIPTOR);
    add(qualitativeHeuristicDescriptorSchema, ontology.common.QualitativeHeuristicDescriptor.class);
    ConceptSchema ssHeuristicDescriptorSchema = new ConceptSchema(SSHEURISTICDESCRIPTOR);
    add(ssHeuristicDescriptorSchema, ontology.common.SSHeuristicDescriptor.class);
    ConceptSchema msHeuristicDescriptorSchema = new ConceptSchema(MSHEURISTICDESCRIPTOR);
    add(msHeuristicDescriptorSchema, ontology.common.MSHeuristicDescriptor.class);
    /*ConceptSchema measuringUnitSchema = new ConceptSchema(MEASURINGUNIT);
    add(measuringUnitSchema, ontology.common.MeasuringUnit.class);*/

    // adding AgentAction(s)

    // adding AID(s)

    // adding Predicate(s)

    // adding fields
    descriptorSchema.add(DESCRIPTOR_STRUCTURE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    descriptorSchema.add(DESCRIPTOR_ATTRIBUTE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    svCharacterDescriptorSchema.add(SVCHARACTERDESCRIPTOR_VALUE, singleValueSchema, ObjectSchema.MANDATORY);
    rvCharacterDescriptorSchema.add(RVCHARACTERDESCRIPTOR_VALUE, rangeValueSchema, ObjectSchema.MANDATORY);
    ssCharacterDescriptorSchema.add(SSCHARACTERDESCRIPTOR_VALUE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    msCharacterDescriptorSchema.add(MSCHARACTERDESCRIPTOR_VALUE, (TermSchema)getSchema(BasicOntology.STRING), 2, ObjectSchema.UNLIMITED);
    svHeuristicDescriptorSchema.add(SVHEURISTICDESCRIPTOR_VALUE, singleValueSchema, ObjectSchema.MANDATORY);
    rvHeuristicDescriptorSchema.add(RVHEURISTICDESCRIPTOR_VALUE, rangeValueSchema, ObjectSchema.MANDATORY);
    ssHeuristicDescriptorSchema.add(SSHEURISTICDESCRIPTOR_VALUE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    msHeuristicDescriptorSchema.add(MSHEURISTICDESCRIPTOR_VALUE, (TermSchema)getSchema(BasicOntology.STRING), 2, ObjectSchema.UNLIMITED);
    valueSchema.add(VALUE_MEASURINGUNIT, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    singleValueSchema.add(SINGLEVALUE_VALUE, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    rangeValueSchema.add(RANGEVALUE_LOWERBOUND, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    rangeValueSchema.add(RANGEVALUE_UPPERBOUND, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    descriptionSchema.add(DESCRIPTION_DESCRIPTORS, descriptorSchema, 0, ObjectSchema.UNLIMITED);

    // adding name mappings

    // adding inheritance
    singleValueSchema.addSuperSchema(valueSchema);
    msCharacterDescriptorSchema.addSuperSchema(qualitativeCharacterDescriptorSchema);
    quantitativeCharacterDescriptorSchema.addSuperSchema(characterDescriptorSchema);
    svCharacterDescriptorSchema.addSuperSchema(quantitativeCharacterDescriptorSchema);
    rvCharacterDescriptorSchema.addSuperSchema(quantitativeCharacterDescriptorSchema);
    rangeValueSchema.addSuperSchema(valueSchema);
    characterDescriptorSchema.addSuperSchema(descriptorSchema);
    qualitativeCharacterDescriptorSchema.addSuperSchema(characterDescriptorSchema);
    ssCharacterDescriptorSchema.addSuperSchema(qualitativeCharacterDescriptorSchema);
    quantitativeHeuristicDescriptorSchema.addSuperSchema(heuristicDescriptorSchema);
    svHeuristicDescriptorSchema.addSuperSchema(quantitativeHeuristicDescriptorSchema);
    rvHeuristicDescriptorSchema.addSuperSchema(quantitativeHeuristicDescriptorSchema);
    heuristicDescriptorSchema.addSuperSchema(descriptorSchema);
    qualitativeHeuristicDescriptorSchema.addSuperSchema(heuristicDescriptorSchema);
    ssHeuristicDescriptorSchema.addSuperSchema(qualitativeHeuristicDescriptorSchema);
    msHeuristicDescriptorSchema.addSuperSchema(qualitativeHeuristicDescriptorSchema);

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
